name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # temporary disabling gradle build. Error :
    # An exception occurred applying plugin request [id: 'com.android.application']
    # > Failed to apply plugin 'com.android.internal.version-check'.
    #   > Minimum supported Gradle version is 7.4. Current version is 7.3. If using the gradle wrapper, try editing the distributionUrl in /home/lebocqt/Documents/code/cours/ensicaen-patronusControl-AndroidFrontend/gradle/wrapper/gradle-wrapper.properties to gradle-7.4-all.zip
    # TODO find fix
    # - name: Build with Gradle
    #   run: ./gradlew build
